serviceTree:
  landscape: &landscape entei
  cluster: &cluster mica

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

reloader:
  reloader:
    deployment:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
      annotations:
        <<: *tags
      labels:
        <<: *tags
      pod:
        annotations:
          <<: *tags
