serviceTree:
  landscape: pichu
  cluster: opal


reloader:
  reloader:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
      annotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      labels:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      pod:
        annotations:
          atomi.cloud/landscape: pichu
          atomi.cloud/cluster: opal
