serviceTree:
  landscape: pichu
  cluster: opal
  platform: systems
  service: reloader
  layer: "1"

reloader:
  reloader:
    reloadOnCreate: true
    deployment:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              atomi.cloud/service: reloader
              atomi.cloud/module: operator
      nodeSelector:
        kubernetes.io/os: linux
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
      annotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
        atomi.cloud/platform: systems
        atomi.cloud/service: reloader
        atomi.cloud/module: operator
        atomi.cloud/layer: "1"
      labels:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
        atomi.cloud/platform: systems
        atomi.cloud/service: reloader
        atomi.cloud/module: operator
        atomi.cloud/layer: "1"
      pod:
        annotations:
          atomi.cloud/landscape: pichu
          atomi.cloud/cluster: opal
          atomi.cloud/platform: systems
          atomi.cloud/service: reloader
          atomi.cloud/module: operator
          atomi.cloud/layer: "1"
